### ISSUE TITLE
Crash with Immersive Engineering (1.10.2)

### ISSUE THREAD

**Issue by DarkSlayerEX** [maruohon/placementpreview#5] opened 2016-11-24 18:09 UTC
(edited by masa):
http://pastebin.com/8M01mJMe

**Comment by maruohon** [comment] 2016-11-24 20:25
Are you able to reproduce this crash reliably? Does it happen when previewing a certain block, ie. with a certain item in hand, or simply close to certain IE blocks in-world?

I've gotten several similar crash reports, but I don't know how to reproduce this myself, so finding the cause and proper fix for it is rather difficult...

**Comment by DarkSlayerEX** [comment] 2016-11-27 15:59
It happens any time i try to placement preview it's windmill items. Certain other items appear fine.

I haven't tried any of the other special mechanical objects with it though.

**Comment by maruohon** [comment] 2016-11-27 16:36
Could you post a screenshot of this, showing what blocks are in the world (or does this matter at all?) in what configuration and what is in your hand. Basically just before you would activate the preview and it would crash. Thanks!

**Comment by DarkSlayerEX** [comment] 2016-11-27 18:45
http://pastebin.com/G168ssD4
Second Attempt same modpack, empty inventory brand new world - triggered with windmill in hand.

http://pastebin.com/Zem5Y6ZF
Third Attempt, literally vanilla minus this mod, immersive engineering, and JEI. Empty inventory again, new world, and still using the windmill while activating preview.

**Comment by maruohon** [comment] 2016-11-27 22:39
Alright thanks, I'll look into this as soon as I have the time.

**Comment by maruohon** [comment] 2017-05-01 14:51
Fixed in version 0.3.2 for MC 1.10.2 and version 0.3.3 for MC 1.11.2

**Closed as completed by maruohon** 2017-05-01 14:51 UTC
